INSERT INTO api.cohort (term, academic_year) VALUES ('Fall', '2024-2025');
INSERT INTO api.cohort (term, academic_year) VALUES ('Spring', '2024-2025');
INSERT INTO api.cohort (term, academic_year) VALUES ('Summer', '2024-2025');
INSERT INTO api.cohort (term, academic_year) VALUES ('Fall', '2025-2026');
INSERT INTO api.cohort (term, academic_year) VALUES ('Spring', '2025-2026');
INSERT INTO api.cohort (term, academic_year) VALUES ('Summer', '2025-2026');
INSERT INTO api.cohort (term, academic_year) VALUES ('Fall', '2026-2027');
INSERT INTO api.cohort (term, academic_year) VALUES ('Spring', '2026-2027');
INSERT INTO api.cohort (term, academic_year) VALUES ('Summer', '2026-2027');
INSERT INTO api.cohort (term, academic_year) VALUES ('Fall', '2027-2028');
INSERT INTO api.cohort (term, academic_year) VALUES ('Spring', '2027-2028');
INSERT INTO api.cohort (term, academic_year) VALUES ('Summer', '2027-2028');
INSERT INTO api.cohort (term, academic_year) VALUES ('Fall', '2028-2029');
INSERT INTO api.cohort (term, academic_year) VALUES ('Spring', '2028-2029');
INSERT INTO api.cohort (term, academic_year) VALUES ('Summer', '2028-2029');
INSERT INTO api.cohort (term, academic_year) VALUES ('Fall', '2029-2030');
INSERT INTO api.cohort (term, academic_year) VALUES ('Spring', '2029-2030');
INSERT INTO api.cohort (term, academic_year) VALUES ('Summer', '2029-2030');
INSERT INTO api.cohort (term, academic_year) VALUES ('Fall', '2030-2031');
INSERT INTO api.cohort (term, academic_year) VALUES ('Spring', '2030-2031');
INSERT INTO api.cohort (term, academic_year) VALUES ('Summer', '2030-2031');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Curtis-Bright', '445110', 31, '112 Williams Valleys Suite 363', 'North Paula');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Curry, Weaver and Owen', '722511', 9, '94245 Martin Shoals', 'Timothyside');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Warner LLC', '445110', 7, '2484 Victor Villages', 'Riverahaven');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Alexander-Howard', '722511', 22, '375 Patel Isle Apt. 140', 'Adrianville');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Benson-Harvey', '722511', 30, '9026 Mitchell Inlet Apt. 390', 'North Williamport');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Erickson, Smith and Boyd', '541211', 6, '43373 Chandler Divide', 'South Jessica');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Baldwin-Foster', '722511', 31, '1367 Carter Terrace Apt. 276', 'Allentown');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Farrell-Luna', '445110', 41, '96801 Laura Mountains', 'South Nicholashaven');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Valdez PLC', '722511', 23, '59223 King Islands', 'Port Jenniferland');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Gonzalez-Walker', '541211', 38, '5907 Corey Ville', 'Ramirezchester');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Berger, Curtis and Wilcox', '621210', 23, '6882 Weiss Plaza', 'Duanebury');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Lee, Copeland and Potter', '811212', 38, '50641 Wilson Cliffs Suite 647', 'North Wesleyfurt');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Miller and Sons', '445110', 3, '087 Jensen Plain', 'West Melanie');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Miller Group', '621210', 16, '36432 Justin Trace', 'New Benjamin');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Andrade Ltd', '722511', 6, '770 Jamie Coves Apt. 546', 'North Elizabeth');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Romero, Jones and Martin', '541211', 44, '18145 Middleton Stream', 'West Julia');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Stanton, Ward and Bryant', '811212', 45, '785 Sarah Garden', 'Richardsfort');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Davis, White and Owens', '722511', 19, '18198 Lane Stravenue', 'North Angela');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Burns, Davis and Nguyen', '722511', 40, '40673 Brittany Cliffs', 'Martinezside');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Spence and Sons', '621210', 10, '538 Vega Place Apt. 627', 'West Rebecca');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Mason, Martin and Smith', '621210', 19, '42432 George Tunnel Suite 580', 'Lake Nicholas');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Taylor PLC', '541211', 41, '5730 Willie Underpass Apt. 960', 'Popeview');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Christian PLC', '811212', 5, '1901 Rebecca Common', 'West Lawrencefurt');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Alexander-Krueger', '445110', 40, '843 Johnson Knoll Suite 554', 'West Melissa');
INSERT INTO api.business_client (business_name, naics_code, employee_count, street_address, location) VALUES ('Woods Group', '722511', 45, '0461 Schmidt Lodge', 'Gravesville');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (1, 'Craig', 'Lewis', 'Academic librarian', 'teresalong@example.net');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (2, 'Harold', 'Carpenter', 'Radiation protection practitioner', 'perickson@example.net');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (2, 'Michelle', 'Gordon', 'Museum/gallery curator', 'psmith@example.net');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (3, 'Norman', 'Bond', 'Buyer, industrial', 'garciajulie@example.com');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (4, 'Lacey', 'Lopez', 'Surveyor, minerals', 'sydney38@example.com');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (5, 'Holly', 'Santiago', 'Ergonomist', 'brandon60@example.org');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (6, 'Calvin', 'Lopez', 'Toxicologist', 'victoria89@example.net');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (6, 'Megan', 'Hodges', 'Academic librarian', 'joe54@example.com');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (7, 'Jamie', 'Page', 'Land', 'martinezemma@example.com');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (7, 'Corey', 'Ingram', 'General practice doctor', 'grosselaine@example.com');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (8, 'Joshua', 'Johnson', 'Engineer, water', 'james23@example.com');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (9, 'Timothy', 'Holland', 'Higher education lecturer', 'hharris@example.com');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (9, 'Kristie', 'Miller', 'Furniture designer', 'ajones@example.net');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (10, 'Michael', 'Mcgrath', 'Engineer, chemical', 'anna66@example.com');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (11, 'Erica', 'Tate', 'Financial planner', 'bjones@example.com');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (11, 'Chelsea', 'Rogers', 'Surveyor, insurance', 'michael31@example.org');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (12, 'Hailey', 'Johnson', 'Field trials officer', 'goodwinchristopher@example.org');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (13, 'Edward', 'Williams', 'Speech and language therapist', 'devincummings@example.org');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (13, 'Justin', 'Prince', 'Chartered accountant', 'pshelton@example.net');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (14, 'Allison', 'Cordova', 'Quantity surveyor', 'rebeccahall@example.com');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (14, 'Karen', 'Scott', 'Production designer, theatre/television/', 'nathan30@example.org');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (15, 'Zachary', 'Berry', 'Chartered certified accountant', 'npitts@example.org');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (15, 'James', 'Jackson', 'Psychologist, educational', 'rbarnett@example.com');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (16, 'Matthew', 'Mccormick', 'Graphic designer', 'wchung@example.org');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (16, 'Renee', 'Walker', 'Psychologist, clinical', 'ngreen@example.org');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (17, 'Debbie', 'Clark', 'Charity officer', 'albertjones@example.org');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (18, 'Brian', 'Rodriguez', 'Metallurgist', 'derek21@example.net');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (19, 'Sydney', 'French', 'Police officer', 'brianna07@example.org');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (20, 'Luis', 'Lin', 'Engineer, energy', 'andrew68@example.net');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (21, 'Robin', 'Wilson', 'Designer, television/film set', 'kaitlynedwards@example.org');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (22, 'Jessica', 'Contreras', 'Engineer, manufacturing systems', 'clarkstephanie@example.org');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (22, 'Sarah', 'Moore', 'Engineer, manufacturing systems', 'johnstout@example.org');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (23, 'Taylor', 'Turner', 'Proofreader', 'leemolly@example.com');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (24, 'Erica', 'Walker', 'Counselling psychologist', 'brendan46@example.org');
INSERT INTO api.contact (client_id, first_name, last_name, role, email) VALUES (25, 'Kevin', 'Herman', 'Ship broker', 'kaylazimmerman@example.org');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (3, 'Robert', 'Davis', 'Expert');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (2, 'Tammy', 'Clay', 'Foundation');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (2, 'Jermaine', 'Gibson', 'Professional');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (3, 'Judith', 'Adams', 'Expert');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (1, 'Michael', 'Monroe', 'Foundation');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (3, 'Kimberly', 'Wright', 'Foundation');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (4, 'Matthew', 'Oliver', 'Expert');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (1, 'Samantha', 'Evans', 'Professional');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (3, 'Joel', 'Lopez', 'Expert');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (2, 'Duane', 'Williams', 'Expert');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (3, 'Maurice', 'Mullins', 'Expert');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (3, 'John', 'Glover', 'Professional');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (1, 'Margaret', 'Bowen', 'Expert');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (4, 'Kathy', 'Morgan', 'Expert');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (2, 'Shelly', 'Espinoza', 'Expert');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (2, 'Kenneth', 'Dudley', 'Foundation');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (4, 'Erika', 'Walker', 'Professional');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (1, 'John', 'Leon', 'Professional');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (1, 'Ronnie', 'Price', 'Foundation');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (1, 'Damon', 'Ortiz', 'Professional');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (1, 'Eddie', 'Lopez', 'Expert');
INSERT INTO api.consultant (cohort_id, first_name, last_name, competency_level) VALUES (4, 'Claudia', 'Christian', 'Foundation');
INSERT INTO api.industry_mentor (assigned_cohort_id, first_name, last_name, expertise_area) VALUES (4, 'Ruben', 'Carter', 'Compliance');
INSERT INTO api.industry_mentor (assigned_cohort_id, first_name, last_name, expertise_area) VALUES (2, 'Cynthia', 'Norman', 'Incident Response');
INSERT INTO api.industry_mentor (assigned_cohort_id, first_name, last_name, expertise_area) VALUES (1, 'Chris', 'Robles', 'Network Security');
INSERT INTO api.industry_mentor (assigned_cohort_id, first_name, last_name, expertise_area) VALUES (3, 'Jonathan', 'Atkinson', 'Incident Response');
INSERT INTO api.industry_mentor (assigned_cohort_id, first_name, last_name, expertise_area) VALUES (2, 'Kathleen', 'Hansen', 'Incident Response');
INSERT INTO api.industry_mentor (assigned_cohort_id, first_name, last_name, expertise_area) VALUES (1, 'Taylor', 'Perkins', 'Incident Response');
INSERT INTO api.industry_mentor (assigned_cohort_id, first_name, last_name, expertise_area) VALUES (2, 'Claire', 'Patton', 'Network Security');
INSERT INTO api.industry_mentor (assigned_cohort_id, first_name, last_name, expertise_area) VALUES (1, 'James', 'Armstrong', 'Incident Response');
INSERT INTO api.industry_mentor (assigned_cohort_id, first_name, last_name, expertise_area) VALUES (2, 'Jaime', 'Dunn', 'Identity & Access');
INSERT INTO api.industry_mentor (assigned_cohort_id, first_name, last_name, expertise_area) VALUES (1, 'Dawn', 'Snow', 'Identity & Access');
INSERT INTO api.industry_mentor (assigned_cohort_id, first_name, last_name, expertise_area) VALUES (2, 'Sharon', 'Taylor', 'Network Security');
INSERT INTO api.industry_mentor (assigned_cohort_id, first_name, last_name, expertise_area) VALUES (3, 'Ronald', 'Nunez', 'Incident Response');
INSERT INTO api.industry_mentor (assigned_cohort_id, first_name, last_name, expertise_area) VALUES (4, 'Katherine', 'Cooke', 'Compliance');
INSERT INTO api.industry_mentor (assigned_cohort_id, first_name, last_name, expertise_area) VALUES (3, 'Thomas', 'Becker', 'Network Security');
INSERT INTO api.industry_mentor (assigned_cohort_id, first_name, last_name, expertise_area) VALUES (2, 'Julia', 'Hernandez', 'Identity & Access');
INSERT INTO api.industry_mentor (assigned_cohort_id, first_name, last_name, expertise_area) VALUES (3, 'Steve', 'Larson', 'Incident Response');
INSERT INTO api.industry_mentor (assigned_cohort_id, first_name, last_name, expertise_area) VALUES (1, 'Michael', 'Cole', 'Identity & Access');
INSERT INTO api.industry_mentor (assigned_cohort_id, first_name, last_name, expertise_area) VALUES (2, 'Lindsay', 'Lopez', 'Identity & Access');
INSERT INTO api.industry_mentor (assigned_cohort_id, first_name, last_name, expertise_area) VALUES (3, 'Holly', 'Chambers', 'Network Security');
INSERT INTO api.industry_mentor (assigned_cohort_id, first_name, last_name, expertise_area) VALUES (1, 'Megan', 'Arias', 'Identity & Access');
INSERT INTO api.faculty_advisor (first_name, last_name, department) VALUES ('Christopher', 'Kirk', 'Computer Science');
INSERT INTO api.faculty_advisor (first_name, last_name, department) VALUES ('Natasha', 'Sanchez', 'Cybersecurity');
INSERT INTO api.faculty_advisor (first_name, last_name, department) VALUES ('Wendy', 'Miller', 'Computer Science');
INSERT INTO api.faculty_advisor (first_name, last_name, department) VALUES ('Victoria', 'Wright', 'Computer Science');
INSERT INTO api.faculty_advisor (first_name, last_name, department) VALUES ('Tanner', 'Mason', 'Information Systems');
INSERT INTO api.faculty_advisor (first_name, last_name, department) VALUES ('Amy', 'Davis', 'Computer Science');
INSERT INTO api.faculty_advisor (first_name, last_name, department) VALUES ('Daniel', 'Tran', 'Cybersecurity');
INSERT INTO api.faculty_advisor (first_name, last_name, department) VALUES ('John', 'Watson', 'Information Systems');
INSERT INTO api.faculty_advisor (first_name, last_name, department) VALUES ('Donald', 'Jacobson', 'Cybersecurity');
INSERT INTO api.faculty_advisor (first_name, last_name, department) VALUES ('Pamela', 'Wu', 'Computer Science');
INSERT INTO api.faculty_advisor (first_name, last_name, department) VALUES ('Pamela', 'Hernandez', 'Computer Science');
INSERT INTO api.faculty_advisor (first_name, last_name, department) VALUES ('John', 'Ross', 'Cybersecurity');
INSERT INTO api.faculty_advisor (first_name, last_name, department) VALUES ('Daniel', 'Carter', 'Computer Science');
INSERT INTO api.faculty_advisor (first_name, last_name, department) VALUES ('Kathleen', 'Davies', 'Cybersecurity');
INSERT INTO api.faculty_advisor (first_name, last_name, department) VALUES ('Catherine', 'Tran', 'Cybersecurity');
INSERT INTO api.faculty_advisor (first_name, last_name, department) VALUES ('Ana', 'Watts', 'Information Systems');
INSERT INTO api.faculty_advisor (first_name, last_name, department) VALUES ('Lisa', 'Evans', 'Computer Science');
INSERT INTO api.faculty_advisor (first_name, last_name, department) VALUES ('Angela', 'Ramos', 'Computer Science');
INSERT INTO api.faculty_advisor (first_name, last_name, department) VALUES ('Beth', 'Hooper', 'Computer Science');
INSERT INTO api.faculty_advisor (first_name, last_name, department) VALUES ('Joseph', 'Jones', 'Information Systems');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (20, 8, 17, 16, 'Reviewer');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (11, 13, 17, 7, 'Lead');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (1, 19, 1, 16, 'Lead');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (17, 24, 6, 12, 'Lead');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (5, 20, 3, 3, 'Reviewer');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (22, 3, 15, 11, 'Support');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (7, 14, 9, 2, 'Support');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (12, 1, 3, 13, 'Support');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (7, 25, 5, 7, 'Reviewer');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (15, 16, 5, 2, 'Lead');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (12, 23, 1, 7, 'Lead');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (12, 23, 2, 9, 'Lead');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (5, 3, 9, 16, 'Lead');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (11, 4, 19, 10, 'Reviewer');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (14, 23, 2, 4, 'Lead');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (20, 19, 1, 4, 'Reviewer');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (20, 21, 9, 16, 'Lead');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (16, 12, 20, 10, 'Lead');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (15, 1, 9, 4, 'Support');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (7, 24, 17, 7, 'Reviewer');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (8, 1, 11, 2, 'Reviewer');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (2, 1, 17, 17, 'Lead');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (8, 16, 2, 19, 'Support');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (18, 13, 19, 14, 'Lead');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (19, 4, 19, 8, 'Reviewer');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (12, 13, 1, 15, 'Lead');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (10, 18, 8, 2, 'Lead');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (20, 8, 11, 16, 'Lead');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (17, 4, 5, 13, 'Reviewer');
INSERT INTO api.assignment (consultant_id, client_id, mentor_id, faculty_advisor_id, assigned_role) VALUES (11, 19, 19, 11, 'Lead');
INSERT INTO api.mou (client_id, version) VALUES (1, 'v3.0');
INSERT INTO api.mou (client_id, version) VALUES (2, 'v2.0');
INSERT INTO api.mou (client_id, version) VALUES (3, 'v1.0');
INSERT INTO api.mou (client_id, version) VALUES (4, 'v3.0');
INSERT INTO api.mou (client_id, version) VALUES (5, 'v3.0');
INSERT INTO api.mou (client_id, version) VALUES (6, 'v1.0');
INSERT INTO api.mou (client_id, version) VALUES (7, 'v2.0');
INSERT INTO api.mou (client_id, version) VALUES (8, 'v1.0');
INSERT INTO api.mou (client_id, version) VALUES (9, 'v1.0');
INSERT INTO api.mou (client_id, version) VALUES (10, 'v3.0');
INSERT INTO api.mou (client_id, version) VALUES (11, 'v3.0');
INSERT INTO api.mou (client_id, version) VALUES (12, 'v2.0');
INSERT INTO api.mou (client_id, version) VALUES (13, 'v3.0');
INSERT INTO api.mou (client_id, version) VALUES (14, 'v1.0');
INSERT INTO api.mou (client_id, version) VALUES (15, 'v1.0');
INSERT INTO api.mou (client_id, version) VALUES (16, 'v1.0');
INSERT INTO api.mou (client_id, version) VALUES (17, 'v3.0');
INSERT INTO api.mou (client_id, version) VALUES (18, 'v2.0');
INSERT INTO api.mou (client_id, version) VALUES (19, 'v2.0');
INSERT INTO api.mou (client_id, version) VALUES (20, 'v2.0');
INSERT INTO api.mou (client_id, version) VALUES (21, 'v1.0');
INSERT INTO api.mou (client_id, version) VALUES (22, 'v1.0');
INSERT INTO api.mou (client_id, version) VALUES (23, 'v2.0');
INSERT INTO api.mou (client_id, version) VALUES (24, 'v2.0');
INSERT INTO api.mou (client_id, version) VALUES (25, 'v1.0');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (25, 'East LA Chamber', 'Reverse-engineered multi-state projection', 'Converted');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (1, 'LA SBDC', 'Polarized composite moratorium', 'Pending');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (14, 'East LA Chamber', 'Up-sized non-volatile database', 'Pending');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (7, 'LA SBDC', 'Diverse client-driven orchestration', 'Referred elsewhere');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (18, 'LA SBDC', 'Advanced value-added pricing structure', 'Converted');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (13, 'East LA Chamber', 'Managed methodical artificial intelligence', 'Converted');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (8, 'East LA Chamber', 'Right-sized empowering contingency', 'No response');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (5, 'East LA Chamber', 'Operative high-level project', 'No response');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (9, 'LA SBDC', 'Front-line multi-tasking help-desk', 'Pending');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (17, 'SBA', 'Secured secondary system engine', 'No response');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (3, 'LA SBDC', 'Optimized 5thgeneration utilization', 'Converted');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (25, 'CISA Region 9', 'Fully-configurable multi-state ability', 'Converted');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (19, 'SBA', 'Enhanced eco-centric policy', 'No response');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (7, 'SBA', 'Implemented incremental ability', 'No response');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (3, 'SBA', 'Centralized dynamic strategy', 'Converted');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (8, 'East LA Chamber', 'Up-sized foreground synergy', 'Pending');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (16, 'East LA Chamber', 'Reduced web-enabled matrix', 'Pending');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (21, 'LA SBDC', 'Total asymmetric infrastructure', 'Converted');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (3, 'East LA Chamber', 'Business-focused well-modulated standardization', 'Pending');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (18, 'East LA Chamber', 'Cross-platform 4thgeneration protocol', 'Referred elsewhere');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (21, 'SBA', 'Synergized methodical workforce', 'Pending');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (4, 'LA SBDC', 'Persistent value-added archive', 'Converted');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (20, 'SBA', 'Optimized solution-oriented workforce', 'No response');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (16, 'SBA', 'Organized tangible emulation', 'Converted');
INSERT INTO api.partner_referral (client_id, partner_organization, referral_event_name, conversion_outcome) VALUES (12, 'CISA Region 9', 'Persistent 24hour alliance', 'Converted');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (10, 'INSERT', 'business_client');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (7, 'INSERT', 'mou');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (10, 'INSERT', 'contact');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (17, 'DELETE', 'assignment');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (6, 'INSERT', 'contact');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (4, 'LOGIN', 'mou');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (14, 'INSERT', 'business_client');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (4, 'INSERT', 'contact');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (9, 'LOGIN', 'assignment');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (20, 'LOGIN', 'business_client');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (16, 'INSERT', 'business_client');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (13, 'INSERT', 'assignment');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (22, 'DELETE', 'business_client');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (8, 'LOGIN', 'assignment');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (13, 'UPDATE', 'contact');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (1, 'UPDATE', 'assignment');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (19, 'UPDATE', 'contact');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (12, 'UPDATE', 'mou');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (4, 'INSERT', 'mou');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (4, 'UPDATE', 'mou');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (16, 'DELETE', 'contact');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (7, 'LOGIN', 'mou');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (17, 'DELETE', 'mou');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (16, 'UPDATE', 'business_client');
INSERT INTO api.audit_log_entry (user_id, action_type, target_table) VALUES (3, 'INSERT', 'assignment');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (1, 1, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (1, 2, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (1, 3, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (1, 4, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (1, 5, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (1, 6, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (1, 7, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (1, 8, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (1, 9, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (1, 10, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (2, 1, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (2, 2, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (2, 3, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (2, 4, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (2, 5, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (2, 6, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (2, 7, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (2, 8, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (2, 9, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (2, 10, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (3, 1, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (3, 2, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (3, 3, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (3, 4, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (3, 5, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (3, 6, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (3, 7, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (3, 8, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (3, 9, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (3, 10, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (4, 1, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (4, 2, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (4, 3, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (4, 4, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (4, 5, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (4, 6, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (4, 7, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (4, 8, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (4, 9, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (4, 10, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (5, 1, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (5, 2, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (5, 3, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (5, 4, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (5, 5, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (5, 6, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (5, 7, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (5, 8, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (5, 9, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (5, 10, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (6, 1, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (6, 2, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (6, 3, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (6, 4, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (6, 5, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (6, 6, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (6, 7, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (6, 8, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (6, 9, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (6, 10, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (7, 1, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (7, 2, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (7, 3, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (7, 4, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (7, 5, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (7, 6, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (7, 7, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (7, 8, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (7, 9, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (7, 10, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (8, 1, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (8, 2, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (8, 3, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (8, 4, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (8, 5, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (8, 6, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (8, 7, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (8, 8, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (8, 9, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (8, 10, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (9, 1, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (9, 2, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (9, 3, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (9, 4, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (9, 5, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (9, 6, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (9, 7, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (9, 8, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (9, 9, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (9, 10, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (10, 1, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (10, 2, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (10, 3, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (10, 4, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (10, 5, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (10, 6, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (10, 7, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (10, 8, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (10, 9, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (10, 10, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (11, 1, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (11, 2, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (11, 3, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (11, 4, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (11, 5, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (11, 6, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (11, 7, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (11, 8, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (11, 9, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (11, 10, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (12, 1, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (12, 2, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (12, 3, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (12, 4, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (12, 5, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (12, 6, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (12, 7, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (12, 8, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (12, 9, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (12, 10, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (13, 1, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (13, 2, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (13, 3, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (13, 4, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (13, 5, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (13, 6, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (13, 7, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (13, 8, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (13, 9, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (13, 10, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (14, 1, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (14, 2, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (14, 3, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (14, 4, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (14, 5, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (14, 6, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (14, 7, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (14, 8, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (14, 9, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (14, 10, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (15, 1, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (15, 2, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (15, 3, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (15, 4, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (15, 5, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (15, 6, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (15, 7, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (15, 8, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (15, 9, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (15, 10, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (16, 1, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (16, 2, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (16, 3, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (16, 4, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (16, 5, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (16, 6, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (16, 7, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (16, 8, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (16, 9, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (16, 10, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (17, 1, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (17, 2, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (17, 3, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (17, 4, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (17, 5, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (17, 6, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (17, 7, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (17, 8, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (17, 9, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (17, 10, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (18, 1, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (18, 2, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (18, 3, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (18, 4, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (18, 5, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (18, 6, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (18, 7, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (18, 8, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (18, 9, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (18, 10, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (19, 1, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (19, 2, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (19, 3, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (19, 4, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (19, 5, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (19, 6, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (19, 7, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (19, 8, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (19, 9, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (19, 10, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (20, 1, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (20, 2, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (20, 3, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (20, 4, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (20, 5, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (20, 6, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (20, 7, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (20, 8, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (20, 9, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (20, 10, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (21, 1, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (21, 2, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (21, 3, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (21, 4, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (21, 5, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (21, 6, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (21, 7, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (21, 8, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (21, 9, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (21, 10, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (22, 1, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (22, 2, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (22, 3, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (22, 4, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (22, 5, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (22, 6, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (22, 7, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (22, 8, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (22, 9, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (22, 10, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (23, 1, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (23, 2, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (23, 3, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (23, 4, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (23, 5, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (23, 6, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (23, 7, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (23, 8, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (23, 9, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (23, 10, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (24, 1, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (24, 2, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (24, 3, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (24, 4, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (24, 5, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (24, 6, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (24, 7, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (24, 8, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (24, 9, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (24, 10, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (25, 1, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (25, 2, 'B');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (25, 3, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (25, 4, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (25, 5, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (25, 6, 'D');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (25, 7, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (25, 8, 'C');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (25, 9, 'A');
INSERT INTO api.questionnaire_response (client_id, question_number, answer) VALUES (25, 10, 'C');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Organic logistical circuit', 'Hand clearly ever. High way community itself single.', 'High', 'Thank thing moment open three.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Profit-focused transitional superstructure', 'Foot soon though more. Oil challenge teach national toward his four.', 'Critical', 'Per big impact today standard participant institution.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Up-sized empowering system engine', 'Appear wear parent fine. Stand fire agreement study sister live on next.', 'Low', 'Agreement matter three card look law morning. Cause improve maybe history good.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Open-architected national algorithm', 'On successful ground send. Treatment then rich common accept daughter.', 'High', 'Style behind relate establish yet floor.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Networked dedicated architecture', 'Reveal campaign doctor.', 'High', 'Compare interview board could bed. Way accept social many.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Exclusive interactive migration', 'His business help table economic start audience. Few let determine understand lead fast movie.', 'Medium', 'Rich eight property thousand can film cut. Rest son open water government wind various.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Multi-channeled fresh-thinking process improvement', 'Peace garden list action still feel nor. Understand kitchen carry.', 'Critical', 'Player city available seven.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Automated leadingedge archive', 'Me ago often church provide population account fill. Economic thing song vote. Military discussion price live purpose because more central.', 'Critical', 'Usually another should sell four. Board ago religious news again whole yes.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Organized exuding middleware', 'Determine political simple answer. Medical rock lose where young three whose. Central hot have add sell computer serve example. Financial again with area difficult.', 'Critical', 'Up real nearly.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Multi-lateral background capability', 'Protect price me development professor appear six. Several would class risk often rise clearly.', 'Critical', 'Number forget past citizen support. Economic relate democratic different ok money cell crime.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Ergonomic executive emulation', 'Hit stay economy. Green mouth camera skin maintain team.', 'Low', 'School low while discussion doctor find nice discussion.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Future-proofed executive approach', 'Meeting leader side seven building law. Add itself someone there girl believe.', 'Low', 'Argue attorney huge chair. Between condition in marriage citizen wall hope.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Object-based local open system', 'Experience half reach stuff almost air only throughout. Every carry agent. Mouth answer anyone list determine.', 'Critical', 'International thousand west among phone. Cause play man his page some kind.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Balanced solution-oriented infrastructure', 'Image suggest management measure when past. Clear world language human everything specific. Become before think home difficult body.', 'High', 'Lawyer ever special mean heart good Republican.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Cross-group actuating forecast', 'Past door front new political main. We grow language. Form consumer help walk letter.', 'Critical', 'Trade police as central very result great.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Fundamental regional open system', 'Six above treatment establish area despite how. Page also sometimes executive region money break.', 'Critical', 'Out job financial improve mind. Indeed future check both others ever general travel.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Self-enabling responsive Graphic Interface', 'Federal another imagine Republican head will break economy. Old nothing family item heavy.', 'Low', 'Room minute term. Enter because tree man they offer character time.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Seamless non-volatile strategy', 'Behind phone walk war fund raise west grow. State scene popular likely training. Listen eye return no support.', 'Low', 'Despite maintain firm recent.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Focused web-enabled success', 'Learn economic system five. A compare after.', 'High', 'Public keep hour game left. Miss health draw early participant land evening.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Monitored heuristic functionalities', 'As few apply here.', 'Low', 'Prove east accept possible discussion study think.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Function-based bifurcated installation', 'Truth he address son nor image or.', 'Critical', 'Writer water course admit perhaps song stock eat. Job design follow tonight rather center.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Adaptive client-driven open architecture', 'During you consider garden only fast store.', 'Medium', 'Six stage community forget technology small energy. Radio account of couple plant none improve.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Enhanced high-level project', 'Without behind office because mission. Buy though debate will source and.', 'Low', 'Possible which whom east their race huge. Outside life notice because hit.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Cross-platform solution-oriented ability', 'Early nothing theory. Paper more up eight. Such throughout together hospital blue determine black. Rule husband chance case television.', 'Medium', 'Million weight would lead create table pretty provide. Entire company process ten compare brother.');
INSERT INTO api.knowledge_base_entry (title, finding, severity, remediation) VALUES ('Stand-alone asymmetric algorithm', 'Heart newspaper marriage about arm seem fall. Able us career house. Message institution religious example Democrat. Responsibility responsibility light blue analysis none room.', 'Critical', 'Draw he allow three.');